'use strict';

const _IE = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z"/><path d="m15 5 4 4"/></svg>`;
const _E = (id, nombre, precio) => ({ id, nombre, precio, categoria: 'ESCOLAR', categColor: '#EDE9FE', categText: '#5B21B6', bgImg: '#F3E8FF', iconColor: '#9333EA', icon: _IE });

const PRODUCTOS_ESCOLAR = [
  _E('esc-0',  'ACUARELAS X12 COLORES SIMBAL',                                   3400),
  _E('esc-1',  'AVON BLOCK A5 X80H',                                              2600),
  _E('esc-2',  'AVON BLOCK A6 LISO XU',                                           1600),
  _E('esc-3',  'AVON-EXITO BLOCK ESPIRALADO A5 X80H XU',                          4000),
  _E('esc-4',  'CARTELES DE GOMA EVA XU',                                         1000),
  _E('esc-5',  'CARTULINA BLANCA XU',                                               900),
  _E('esc-6',  'CARTULINA COLOR XU',                                               1100),
  _E('esc-7',  'CARTULINA IMPRESA',                                                1100),
  _E('esc-8',  'CIF REPUESTO LIMPIA VIDRIO 450CC XU',                             3500),
  _E('esc-9',  'COMPAS STUDY XU',                                                  3990),
  _E('esc-10', 'CRAYONES MAXI X8 SIMBAL',                                         3500),
  _E('esc-11', 'CRAYONES X12U SIMBAL',                                             2000),
  _E('esc-12', 'CRAYONES X6 JUMBO SIMBAL',                                        2250),
  _E('esc-13', 'CRAYONES X6U SIMBAL',                                              1200),
  _E('esc-14', 'CUADERNO 15.9X21.1 X80H ESPIRALADO AMERICA',                      1650),
  _E('esc-15', 'CUADERNO EXITO 16X21 X48H T/DURA XU',                             4000),
  _E('esc-16', 'CUADERNO EXITO AB3 X48H T/DURA XU',                               7000),
  _E('esc-17', 'CUADERNO EXITO ESPIRALADO N7 X100H XU',                           9900),
  _E('esc-18', 'CUADERNO LAPRIDA AB3 X50H',                                        4000),
  _E('esc-19', 'CUADERNO LAPRIDA AB3 X50H (EXITO)',                               13000),
  _E('esc-20', 'CUADERNO LAPRIDA N3 50H',                                          4200),
  _E('esc-21', 'CUADERNO LAPRIDA N3 50H (EXITO)',                                  5000),
  _E('esc-22', 'CUADERNO PAPEL NATURAL ESPIRALADO RAY/LIS 70H XU',                3500),
  _E('esc-23', 'CUADERNO PAPEL NATURAL T/FLEXIBLE 42H RAYA/PUNT XU',              2600),
  _E('esc-24', 'CUADERNO RIVADAVIA ABC X50H (EXITO)',                              8500),
  _E('esc-25', 'CUADERNO RIVADAVIA ABC X50H',                                      6500),
  _E('esc-26', 'CUADERNO RIVADAVIA X50H',                                          5500),
  _E('esc-27', 'CUADERNO RIVADAVIA X50H (EXITO)',                                 12000),
  _E('esc-28', 'CUADERNO RIVADAVIA X96H (EXITO)',                                 21250),
  _E('esc-29', 'CUADERNO RIVADAVIA X96H',                                         12000),
  _E('esc-30', 'CUADERNO T/FLEXIBLE X48H AMERICA',                                1500),
  _E('esc-31', 'CUADERNO UNIVERSITARIO',                                           3500),
  _E('esc-32', 'CUTER REPUESTO CHICO X10U',                                        4000),
  _E('esc-33', 'CUTER REPUESTO GRANDE X10U',                                       2500),
  _E('esc-34', 'ESCUADRA 21CM XU',                                                 1400),
  _E('esc-35', 'EXITO BLOCK NEGRO N5 XU',                                          3800),
  _E('esc-36', 'FABER LAPIZ CORRECTOR XU',                                         1800),
  _E('esc-37', 'FILGO REPUESTO JUMP GO! BORRABLE XU',                             1000),
  _E('esc-38', 'FUNDA P/CUADERNO AB3 XU',                                          2000),
  _E('esc-39', 'GENIO REPUESTO ROLLE GEL BORRABLE X3 SIMBAL',                     2800),
  _E('esc-40', 'GENIO-FILGO REPUESTO ROLLER GEL BORRABLE',                        1800),
  _E('esc-41', 'GOMA BLANCA XU MAPED',                                              500),
  _E('esc-42', 'GOMA CANDY RETRACTIL MAPED',                                        900),
  _E('esc-43', 'GOMA EVA GLITER A4 XU',                                            1000),
  _E('esc-44', 'GOMA EVA GLITER Y ADHESIVO XU',                                    2000),
  _E('esc-45', 'GOMA EVA METALIZADA',                                               1900),
  _E('esc-46', 'GOMA EVA XU',                                                       1000),
  _E('esc-47', 'GOMA OLLIE XU SIMBAL',                                               600),
  _E('esc-48', 'GOMA TINTA SIMBAL',                                                  200),
  _E('esc-49', 'GOMA TINTA XU MAPED',                                               800),
  _E('esc-50', 'LAPICES COLOR CORTO X6 SIMBAL',                                    1150),
  _E('esc-51', 'LAPIZ COLOR CORTO X12 SIMBAL',                                     2800),
  _E('esc-52', 'LAPIZ COLOR LARGO X12U SIMBAL',                                    3900),
  _E('esc-53', 'LAPIZ COLORPEPS MINI X12U MAPED',                                  4500),
  _E('esc-54', 'LAPIZ COLORPEPS MINI X6U MAPED',                                   2800),
  _E('esc-55', 'LAPRIDA REPUESTO 480H',                                            21250),
  _E('esc-56', 'LAPRIDA REPUESTO 48H',                                              5000),
  _E('esc-57', 'LAPRIDA REPUESTO A4 X48H',                                         7000),
  _E('esc-58', 'LAPRIDA REPUESTO N3 24H',                                           3500),
  _E('esc-59', 'MASA P/MODELAR XU',                                                  900),
  _E('esc-60', 'PAPEL CREPE XU',                                                    1000),
  _E('esc-61', 'PINCEL 12 XU',                                                      1200),
  _E('esc-62', 'PINCEL 8 XU',                                                        900),
  _E('esc-63', 'PINCEL N-10',                                                        1000),
  _E('esc-64', 'PINCEL N6 XU',                                                       800),
  _E('esc-65', 'PINCELETA N4 XU',                                                   1500),
  _E('esc-66', 'PLASTICOLA COLOR 40G XU',                                           1700),
  _E('esc-67', 'PLASTICOLA TRADICIONAL 40G XU',                                    1500),
  _E('esc-68', 'PLASTILINA X12U',                                                   3100),
  _E('esc-69', 'REGLA 15CM XU',                                                      600),
  _E('esc-70', 'REGLA 20CM XU',                                                      700),
  _E('esc-71', 'REGLA 30CM XU',                                                     1000),
  _E('esc-72', 'REGLA FLEXIBLE 20CM',                                               2000),
  _E('esc-73', 'REGLA METAL 30CM XU',                                               6400),
  _E('esc-74', 'REGLA METAL 40CM XU',                                               7500),
  _E('esc-75', 'REPUESTO CANSON N6 BLANCO',                                         3000),
  _E('esc-76', 'REPUESTO CANSON N3 BLANCO',                                         1000),
  _E('esc-77', 'REPUESTO CANSON N3 COLOR-NEGRO',                                    1500),
  _E('esc-78', 'REPUESTO CANSON N5 BLANCO',                                         1500),
  _E('esc-79', 'REPUESTO CANSON N5 COLOR-NEGRO',                                    2000),
  _E('esc-80', 'REPUESTO CANSON N6 NEGRO-COLOR',                                    3500),
  _E('esc-81', 'RIVADAVIA REPUESTO 24H',                                            3500),
  _E('esc-82', 'RIVADAVIA REPUESTO 480H',                                          21250),
  _E('esc-83', 'RIVADAVIA REPUESTO 48H',                                            6500),
  _E('esc-84', 'SACAPUNTAS CON GOMA 2EN1 XU MAPED',                               2900),
  _E('esc-85', 'SACAPUNTAS DE METAL XU',                                            2000),
  _E('esc-86', 'SACAPUNTAS EJET XU MAPED',                                          1900),
  _E('esc-87', 'SACAPUNTAS IGLU XU MAPED',                                          1300),
  _E('esc-88', 'SACAPUNTAS METAL DOBLE XU',                                         3500),
  _E('esc-89', 'STAEDTLER GOMA BLANCA XU',                                          1800),
  _E('esc-90', 'TEMPERA 250CC XU',                                                   3000),
  _E('esc-91', 'TEMPERA X12U',                                                       3200),
  _E('esc-92', 'TIJERA 17CM XU MAPED',                                              3700),
  _E('esc-93', 'TIJERA 21CM XU MAPED',                                              4500),
  _E('esc-94', 'TIJERA CONFORT 18CM XU SIMBAL',                                     4250),
  _E('esc-95', 'TIJERA SEGURITY XU',                                                 3300),
  _E('esc-96', 'TIJERA XU ESCOLAR SIMBAL',                                           1500),
  _E('esc-97', 'TRANSPORTADOR XU',                                                    800),
];
